# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/rafaelszuminski/CLionProjects/CS1A_WORKSPACE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/rafaelszuminski/CLionProjects/CS1A_WORKSPACE

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/rafaelszuminski/CLionProjects/CS1A_WORKSPACE/CMakeFiles /Users/rafaelszuminski/CLionProjects/CS1A_WORKSPACE/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/rafaelszuminski/CLionProjects/CS1A_WORKSPACE/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named untitled

# Build rule for target.
untitled: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 untitled
.PHONY : untitled

# fast build rule for target.
untitled/fast:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/build
.PHONY : untitled/fast

CalcFunctions/area.o: CalcFunctions/area.cpp.o

.PHONY : CalcFunctions/area.o

# target to build an object file
CalcFunctions/area.cpp.o:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/CalcFunctions/area.cpp.o
.PHONY : CalcFunctions/area.cpp.o

CalcFunctions/area.i: CalcFunctions/area.cpp.i

.PHONY : CalcFunctions/area.i

# target to preprocess a source file
CalcFunctions/area.cpp.i:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/CalcFunctions/area.cpp.i
.PHONY : CalcFunctions/area.cpp.i

CalcFunctions/area.s: CalcFunctions/area.cpp.s

.PHONY : CalcFunctions/area.s

# target to generate assembly for a file
CalcFunctions/area.cpp.s:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/CalcFunctions/area.cpp.s
.PHONY : CalcFunctions/area.cpp.s

CalcFunctions/calc_main.o: CalcFunctions/calc_main.cpp.o

.PHONY : CalcFunctions/calc_main.o

# target to build an object file
CalcFunctions/calc_main.cpp.o:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/CalcFunctions/calc_main.cpp.o
.PHONY : CalcFunctions/calc_main.cpp.o

CalcFunctions/calc_main.i: CalcFunctions/calc_main.cpp.i

.PHONY : CalcFunctions/calc_main.i

# target to preprocess a source file
CalcFunctions/calc_main.cpp.i:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/CalcFunctions/calc_main.cpp.i
.PHONY : CalcFunctions/calc_main.cpp.i

CalcFunctions/calc_main.s: CalcFunctions/calc_main.cpp.s

.PHONY : CalcFunctions/calc_main.s

# target to generate assembly for a file
CalcFunctions/calc_main.cpp.s:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/CalcFunctions/calc_main.cpp.s
.PHONY : CalcFunctions/calc_main.cpp.s

CalcFunctions/circumference.o: CalcFunctions/circumference.cpp.o

.PHONY : CalcFunctions/circumference.o

# target to build an object file
CalcFunctions/circumference.cpp.o:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/CalcFunctions/circumference.cpp.o
.PHONY : CalcFunctions/circumference.cpp.o

CalcFunctions/circumference.i: CalcFunctions/circumference.cpp.i

.PHONY : CalcFunctions/circumference.i

# target to preprocess a source file
CalcFunctions/circumference.cpp.i:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/CalcFunctions/circumference.cpp.i
.PHONY : CalcFunctions/circumference.cpp.i

CalcFunctions/circumference.s: CalcFunctions/circumference.cpp.s

.PHONY : CalcFunctions/circumference.s

# target to generate assembly for a file
CalcFunctions/circumference.cpp.s:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/CalcFunctions/circumference.cpp.s
.PHONY : CalcFunctions/circumference.cpp.s

CalcFunctions/dist.o: CalcFunctions/dist.cpp.o

.PHONY : CalcFunctions/dist.o

# target to build an object file
CalcFunctions/dist.cpp.o:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/CalcFunctions/dist.cpp.o
.PHONY : CalcFunctions/dist.cpp.o

CalcFunctions/dist.i: CalcFunctions/dist.cpp.i

.PHONY : CalcFunctions/dist.i

# target to preprocess a source file
CalcFunctions/dist.cpp.i:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/CalcFunctions/dist.cpp.i
.PHONY : CalcFunctions/dist.cpp.i

CalcFunctions/dist.s: CalcFunctions/dist.cpp.s

.PHONY : CalcFunctions/dist.s

# target to generate assembly for a file
CalcFunctions/dist.cpp.s:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/CalcFunctions/dist.cpp.s
.PHONY : CalcFunctions/dist.cpp.s

CalcFunctions/rad.o: CalcFunctions/rad.cpp.o

.PHONY : CalcFunctions/rad.o

# target to build an object file
CalcFunctions/rad.cpp.o:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/CalcFunctions/rad.cpp.o
.PHONY : CalcFunctions/rad.cpp.o

CalcFunctions/rad.i: CalcFunctions/rad.cpp.i

.PHONY : CalcFunctions/rad.i

# target to preprocess a source file
CalcFunctions/rad.cpp.i:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/CalcFunctions/rad.cpp.i
.PHONY : CalcFunctions/rad.cpp.i

CalcFunctions/rad.s: CalcFunctions/rad.cpp.s

.PHONY : CalcFunctions/rad.s

# target to generate assembly for a file
CalcFunctions/rad.cpp.s:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/CalcFunctions/rad.cpp.s
.PHONY : CalcFunctions/rad.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... untitled"
	@echo "... CalcFunctions/area.o"
	@echo "... CalcFunctions/area.i"
	@echo "... CalcFunctions/area.s"
	@echo "... CalcFunctions/calc_main.o"
	@echo "... CalcFunctions/calc_main.i"
	@echo "... CalcFunctions/calc_main.s"
	@echo "... CalcFunctions/circumference.o"
	@echo "... CalcFunctions/circumference.i"
	@echo "... CalcFunctions/circumference.s"
	@echo "... CalcFunctions/dist.o"
	@echo "... CalcFunctions/dist.i"
	@echo "... CalcFunctions/dist.s"
	@echo "... CalcFunctions/rad.o"
	@echo "... CalcFunctions/rad.i"
	@echo "... CalcFunctions/rad.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

